### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by pavanvo** [krzmig/godot-simple-sky-project#2]
Faced with the problem that the shadows are not displayed.

I was trying to implement a simple sun clock.

The shadows enabled but light energy is turns to `0` when I run the `AnimationPlayer`, I also was trying to run with `1` - shadows also not works
![image](https://github.com/krzmig/godot-simple-sky-project/assets/44589046/17b67689-f489-4e99-a629-061d9b3f0b15)

Here DirectionalLight3D with shadows enabled
![image](https://github.com/krzmig/godot-simple-sky-project/assets/44589046/3e46d1ec-d9e9-44ac-a483-8dd88d6143ea)

**Comment by pavanvo** [comment]
Oh, I finnaly got it, need to setup `Light and Sky` mode for sun and moon, and raise light energy from `0`
![image](https://github.com/krzmig/godot-simple-sky-project/assets/44589046/3e1f3f79-a7a3-48ad-8389-5b56ef3a09e7)

**Comment by krzmig** [comment]
Hi, I noticed this as I was working with this sky for my game. I set the lights wrong and it often set the strength of the lights to 0. I will try to correct this soon.

**Comment by krzmig** [comment]
I added parameters to set the strength of the light in the main scene, because with dynamic picking, it can pick up the wrong values, depending on what time you start. It can, for example, download for the sun a power of 0, if you run at night.
![obraz](https://github.com/krzmig/godot-simple-sky-project/assets/10886101/585ff6b9-a76e-434e-8ad7-5942d5e5d730)
Sky mode restored to default.
